{% set version = '1.3.2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-hwriter
  version: {{ version|replace("-", "_") }}

source:
  fn: hwriter_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/hwriter_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/hwriter/hwriter_{{ version }}.tar.gz
  sha256: 6b3531d2e7a239be9d6e3a1aa3256b2745eb68aa0bdffd2076d36552d0d7322b

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1002
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('hwriter')"           # [not win]
    - "\"%R%\" -e \"library('hwriter')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=hwriter
  license: LGPL-2.1
  summary: Easy-to-use and versatile functions to output R objects in HTML format
  license_family: LGPL

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
