appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: nQW3EhYsvMlI4olWcqOp9fZdkRiZtdwmnmhSXTQ8MDfX2bO1bQZhA3juWpccrMwa1m5QUNg9coLqgaZoCc6DfmPAoZsEixvgnBwuBxr2uQf80B0DAzDVRtacFrpm1/U9AJQlZe4ZGhjkHSk9AjXWRTQmInzL5X4NaX1Z/cpDpe90eMYl+JI8YnAVhBGFOxss4HTTvwyX6uUv7l4C5nbccJh0uiHUCbbQFvcWYhscASTQ154lpDE8F8Rol5D4jQgOhTamdtjeUvw8VXdssmD/IYfHUzya9fJGheNkBdelXBwQWtcbKX/HCi1VWyWiDfjeEmiKfHLZzYGNrGxtKvKVRSa7eLMEfrPjIOMdOal1KHpQKMasfhNANOj9WF6cO+BSeYEnYcvb+AApUVhVdkokmjZFFT1KGS1q4oCShVKdKCyst39S8PfNiN+PuxJnEgnbR4FcKgBgKq4pN0Bfilp/jHX71p619q9QljGmP9zdJLy7m5MBkBoE6bvxDSqaa1LAScmrDqQLUk2hFKJUD1VXmWkxr653H78Eit7z5mDc8C8ptAYwWmlyciRPAYLRWmIz50qkaOh1gzFo0iyFNBwZsUTV7YxwfGiFpB9zMdC8Bwe80/joyd+1VQOBanUudNP9eJ5ZF32cxX7RMh1eVBqDSwSM5CTUf0mmfQctoPLxbYo=}
bot:
  automerge: true
